-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 21:56:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seminarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seminarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seminarios` DEFAULT CHARACTER SET utf8 ;
USE `seminarios` ;

-- -----------------------------------------------------
-- Table `seminarios`.`seminario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminarios`.`seminario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(120) NOT NULL,
  `aluno_id` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seminario_aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_seminario_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `seminarios`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `seminarios`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminarios`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `seminarios`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminarios`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
